services:
  mariadb:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: passwort
      MYSQL_DATABASE: skillforge_db
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: dbpasswort
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mariadb
      PMA_USER: dbuser
      PMA_PASSWORD: dbpasswort

volumes:
  mariadb_data:
    driver: local
