import 'package:flutter/material.dart';
import 'package:universal_io/io.dart';

class AppStrings {
  static String appTitle = 'Skillforge';
  static String hompageTitle = 'Skillforge';
  static String english = 'en';
  static String chinese = 'zh';
  static String german = 'de';
  static String yearLabel = 'Year';
  static String monthLabel = 'Month';
  static String weekLabel = 'Week';
  static String resetLabel = 'Reset';
  static String invalidCaptcha = 'Invalid captcha. Please try again.';
  static String failedLogin = 'Login failed';
  static String networkError = 'Network error. Please try again.';
  static String login = 'Login';
  static String username = 'Username';
  static String insertUsername = 'Please enter a username';
  static String password = 'Password';
  static String insertPassword = 'Please enter a password';
  static String captcha = 'Input Captcha';
  static String insertCaptcha = 'Please enter the Captcha code';
  static String wrongCaptcha = 'Invalid Captcha code';
  static String rememberMe = 'Remember me';
  static String forgotPassword = 'Forgot password?';
  static String resetPassword = 'Reset password';
  static String loginSuccessful = 'Login successful. Hello,';
  static String logoutSuccessful = 'Logout successful. See you soon';
  static String filterOptions = 'Filter Options';
  static String filterByUser = 'Show only my events';
  static String loginToFilter = 'Please log in to filter by user.';
  static String eventType = 'Event Type';
  static String subjectArea = 'Subject Area';
  static String clearFilters = 'Clear Filters';
  static String applyFilters = 'Apply Filters';
  static String newYear = 'New Year';
  static String firstMay = 'Labour Day';
  static String germanUnity = 'Anniversary of the German Unification';
  static String christmas1 = 'First Christmas Day';
  static String christmas2 = 'Second Christmas Day';
  static String carFriday = 'Good Friday';
  static String easterSunday = 'Easter Sunday';
  static String easterMonday = 'Easter Monday';
  static String christHeavenDrive = 'Ascension of Christ';
  static String whitSunday = 'Whit Sunday';
  static String whitMonday = 'Whit Monday';
  static String epiphany = 'Epiphany';
  static String intlWomen = 'International Women`s Day';
  static String happyCadaver = 'Corpus Christi';
  static String peaceParty = 'Augsburg`s High Festival of Peace';
  static String mariaHeavenDrive = 'Assumption Day';
  static String worldChildDay = 'World Children`s Day';
  static String reformationDay = 'Reformation Day';
  static String allSaints = 'All Saints` Day';
  static String failedToLoadEventDetails = 'Failed to load event details.';
  static String failedToCheckRegistrationStatus =
      'Failed to check registration status.';
  static String registrationSuccessful =
      'Successfully registered for the event.';
  static String registrationFailed = 'Registration failed.';
  static String cancellationSuccessful =
      'Successfully canceled your registration.';
  static String cancellationFailed = 'Cancellation failed.';
  static String appointmentDetails = 'Appointment Details';
  static String noEventDetails = 'No event details available.';
  static String cancelRegistration = 'Cancel Registration';
  static String registerForEvent = 'Register for Event';
  static String loginRequired = 'Login required to perform this action.';
  static String participants = 'Participants';
  static String eventDates = 'Event Dates';
  static String minParticipants = 'Min Participants';
  static String maxParticipants = 'Max Participants';
  static String currentParticipants = 'Current Participants';
  static String participantInfo = 'Participant Information';
  static String noAppointments = 'No appointments available';
  static String eventSuccessful = 'Event creation successful with ID:';
  static String eventNotSuccessful = 'Event creation failed';
  static String networkError2 = 'Network error:';
  static String accesDenied = 'Access denied';
  static String notAuthorized = 'You are not authorized to access this page.';
  static String adminPanel = 'Admin Panel for creating Events';
  static String autoTranslate = 'Auto Translate';
  static String inputLanguage = 'Input Language';
  static String nameDE = 'Name (DE)';
  static String enterStringDE = 'Please enter the name in German';
  static String nameEN = 'Name (EN)';
  static String enterStringEN = 'Please enter the name in English';
  static String nameZH = 'Name (ZH)';
  static String enterStringZH = 'Please enter the name in Chinese';
  static String descriptionDE = 'Description (DE)';
  static String enterDescriptionDE = 'Please enter the description in German';
  static String descriptionEN = 'Description (EN)';
  static String enterDescriptionEN = 'Please enter the description in English';
  static String descriptionZH = 'Description (ZH)';
  static String enterDescriptionZH = 'Please enter the description in Chinese';
  static String enterMinParticipants = 'Enter min participants';
  static String enterMaxParticipants = 'Enter max participants';
  static String eventDays = 'Event Days';
  static String date = 'Date';
  static String selectDate = 'Please select a date';
  static String startTime = 'Start Time';
  static String selectStartTime = 'Please select start time';
  static String endTime = 'End Time';
  static String selectEndTime = 'Please select end time';
  static String location = 'Location';
  static String enterLocation = 'Please enter a Location';
  static String federalState = 'Federal State';
  static String enterFederalState = 'Please enter a federal state';
  static String removeDay = 'Remove Day';
  static String addEventDay = 'Add another Event Day';
  static String createEvent = 'Create Event';

  static Locale checkLanguage() {
    switch (Platform.localeName.substring(0, 2)) {
      case 'de':
        return const Locale('de');
      case 'zh':
        return const Locale('zh');
      default:
        return const Locale('en');
    }
  }

  static void refreshLanguage(String language) {
    switch (language) {
      case 'de':
        appTitle = 'Skillforge';
        hompageTitle = 'Skillforge';
        english = 'en';
        chinese = 'zh';
        german = 'de';
        yearLabel = 'Jahr';
        monthLabel = 'Monat';
        weekLabel = 'Woche';
        resetLabel = 'Zurücksetzen';
        invalidCaptcha = 'Ungültiges Captcha. Bitte versuche es erneut.';
        failedLogin = 'Anmelden fehlgeschlagen';
        networkError = 'Netzwerkfehler. Bitte versuche es erneut.';
        login = 'Anmelden';
        username = 'Nutzername';
        insertUsername = 'Bitte gebe den Nutzername ein';
        password = 'Passwort';
        insertPassword = 'Bitte gebe das Passwort ein';
        captcha = 'Captcha Eingabe';
        insertCaptcha = 'Bitte gebe den Captcha Code ein';
        wrongCaptcha = 'Ungültiger Captcha Code';
        rememberMe = 'Angemeldet bleiben';
        forgotPassword = 'Passwort vergessen?';
        resetPassword = 'Passwort zurücksetzten';
        loginSuccessful = 'Anmeldung erfolgreich. Hallo,';
        logoutSuccessful = 'Logout erfolgreich. Bis bald';
        filterOptions = 'Filteroptionen';
        filterByUser = 'Nur meine Termine anzeigen';
        loginToFilter =
            'Bitte melden Sie sich zum Filtern nach gebuchten Terminen an.';
        eventType = 'Veranstaltungstyp';
        subjectArea = 'Fachbereich';
        clearFilters = 'Filter löschen';
        applyFilters = 'Filter anwenden';
        newYear = 'Neujahr';
        firstMay = 'Tag der Arbeit';
        germanUnity = 'Tag der Deutschen Einheit';
        christmas1 = 'Erster Weihnachtsfeiertag';
        christmas2 = 'Zweiter Weihnachtsfeiertag';
        carFriday = 'Karfreitag';
        easterSunday = 'Ostersonntag';
        easterMonday = 'Ostermontag';
        christHeavenDrive = 'Christi Himmelfahrt';
        whitSunday = 'Pfingstsonntag';
        whitMonday = 'Pfingstmontag';
        epiphany = 'Heilige Drei Könige';
        intlWomen = 'Internationaler Frauentag';
        happyCadaver = 'Fronleichnam';
        peaceParty = 'Augsburger Hohes Friedensfest';
        mariaHeavenDrive = 'Mariä Himmelfahrt';
        worldChildDay = 'Weltkindertag';
        reformationDay = 'Reformations Tag';
        allSaints = 'Allerheiligen';
        failedToLoadEventDetails =
            'Veranstaltungsdetails konnten nicht geladen werden.';
        failedToCheckRegistrationStatus =
            'Anmeldestatus konnte nicht überprüft werden.';
        registrationSuccessful =
            'Erfolgreich für die Veranstaltung angemeldet.';
        registrationFailed = 'Anmeldung fehlgeschlagen.';
        cancellationSuccessful = 'Anmeldung erfolgreich storniert.';
        cancellationFailed = 'Stornierung fehlgeschlagen.';
        appointmentDetails = 'Veranstaltungsdetails';
        noEventDetails = 'Keine Veranstaltungsdetails verfügbar.';
        cancelRegistration = 'Anmeldung stornieren';
        registerForEvent = 'Für Veranstaltung anmelden';
        loginRequired = 'Anmeldung erforderlich, um diese Aktion auszuführen.';
        participants = 'Teilnehmer';
        eventDates = 'Veranstaltungstermine';
        minParticipants = 'Minimale Teilnehmer';
        maxParticipants = 'Maximale Teilnehmer';
        currentParticipants = 'Aktuelle Teilnehmer';
        participantInfo = 'Teilnehmerinformationen';
        noAppointments = 'Keine Termine vorhanden';
        eventSuccessful = 'Eventerstellung erfolgreich unter ID:';
        eventNotSuccessful = 'Eventerstellung fehlgeschlagen';
        networkError2 = 'Netzwerkfehler:';
        accesDenied = 'Zugriff verweigert';
        notAuthorized = 'Sie sind nicht berechtigt diese Seite zu besuchen.';
        adminPanel = 'Admin Seite zur Eventerstellung';
        autoTranslate = 'Automatische Übersetzung';
        inputLanguage = 'Eingabesprache';
        nameDE = 'Name (DE)';
        enterStringDE = 'Bitte geben sie den Namen in deutsch ein';
        nameEN = 'Name (EN)';
        enterStringEN = 'Bitte geben sie den Namen in englisch ein';
        nameZH = 'Name (ZH)';
        enterStringZH = 'Bitte geben sie den Namen in chinesisch ein';
        descriptionDE = 'Beschreibung (DE)';
        enterDescriptionDE = 'Bitte geben sie die Beschreibung in deutsch ein';
        descriptionEN = 'Beschreibung (EN)';
        enterDescriptionEN = 'Bitte geben sie die Beschreibung in englisch ein';
        descriptionZH = 'Beschreibung (ZH)';
        enterDescriptionZH =
            'Bitte geben sie die Beschreibung in chinesisch ein';
        enterMinParticipants = 'Mindestteilnehmerzahl eingeben';
        enterMaxParticipants = 'Maximalteilnehmerzahl eingeben';
        eventDays = 'Event Termine';
        date = 'Datum';
        selectDate = 'Bitte wählen sie ein Datum';
        startTime = 'Startzeit';
        selectStartTime = 'Bitte wählen sie eine Startzeit';
        endTime = 'Endzeit';
        selectEndTime = 'Bitte wählen sie eine Endzeit';
        location = 'Ort';
        enterLocation = 'Bitte geben sie einen Ort an';
        federalState = 'Bundesland';
        enterFederalState = 'Bitte geben sie ein Bundesland an';
        removeDay = 'Entferne Termin';
        addEventDay = 'Weiteres Datum hinzufügen';
        createEvent = 'Event erstellen';
        break;
      case 'zh':
        appTitle = '技能鍛造';
        hompageTitle = '技能鍛造';
        english = 'en';
        chinese = 'zh';
        german = 'de';
        yearLabel = '年';
        monthLabel = '月';
        weekLabel = '星期';
        resetLabel = '重置';
        invalidCaptcha = '驗證碼無效。請再試一次。';
        failedLogin = '登入失敗';
        networkError = '網路錯誤。請再試一次。';
        login = '登入';
        username = '使用者名稱';
        insertUsername = '請輸入使用者名稱';
        password = '密碼';
        insertPassword = '請輸入密碼';
        captcha = '輸入驗證碼';
        insertCaptcha = '請輸入驗證碼';
        wrongCaptcha = '驗證碼無效';
        rememberMe = '記住帳號';
        loginSuccessful = '登录成功。你好';
        logoutSuccessful = '注销成功。再见';
        forgotPassword = '忘記密碼？';
        resetPassword = '重設密碼';
        filterOptions = '過濾器選項';
        filterByUser = '只顯示我的約會';
        loginToFilter = '請登入以按預訂的約會進行篩選。';
        eventType = '事件類型';
        subjectArea = '部門';
        clearFilters = '清除過濾器';
        applyFilters = '應用過濾器';
        newYear = '新年';
        firstMay = '勞動節';
        germanUnity = '德國統一週年紀念日';
        christmas1 = '第一個聖誕節';
        christmas2 = '第二個聖誕節';
        carFriday = '耶穌受難日';
        easterSunday = '復活節';
        easterMonday = '復活節星期一';
        christHeavenDrive = '基督升天';
        whitSunday = '聖靈降臨節星期日';
        whitMonday = '聖靈降臨節星期一';
        epiphany = '主顯節';
        intlWomen = '國際婦女節';
        happyCadaver = '科珀斯克里斯蒂';
        peaceParty = '奧格斯堡和平盛宴';
        mariaHeavenDrive = '聖母升天日';
        worldChildDay = '世界兒童日';
        reformationDay = '宗教改革日';
        allSaints = '諸聖節';
        failedToLoadEventDetails = '無法載入事件詳細資訊。';
        failedToCheckRegistrationStatus = '無法檢查註冊狀態。';
        registrationSuccessful = '活動報名成功。';
        registrationFailed = '註冊失敗。';
        cancellationSuccessful = '已成功取消您的註冊。';
        cancellationFailed = '取消失敗。';
        appointmentDetails = '預約詳情';
        noEventDetails = '沒有可用的活動詳細資訊。';
        cancelRegistration = '取消註冊';
        registerForEvent = '註冊參加活動';
        loginRequired = '需要登入才能執行此操作。';
        participants = '參加者';
        eventDates = '活動日期';
        minParticipants = '最低參加人數';
        maxParticipants = '最多參加人數';
        currentParticipants = '目前參與者';
        participantInfo = '參與者資訊';
        noAppointments = '沒有可用的預約';
        eventSuccessful = '活動創建成功並帶有識別號碼：';
        eventNotSuccessful = '活動建立失敗';
        networkError2 = '網路錯誤：';
        accesDenied = '拒絕訪問';
        notAuthorized = '您無權存取此頁面。';
        adminPanel = '用於建立事件的管理面板';
        autoTranslate = '自動翻譯';
        inputLanguage = '輸入語言';
        nameDE = '姓名（德國）';
        enterStringDE = '請輸入德語名稱';
        nameEN = '姓名（英文）';
        enterStringEN = '請輸入英文名稱';
        nameZH = '姓名（ZH）';
        enterStringZH = '請輸入中文姓名';
        descriptionDE = '說明（德文）';
        enterDescriptionDE = '請輸入德語描述';
        descriptionEN = '說明（英文）';
        enterDescriptionEN = '請輸入英文描述';
        descriptionZH = '說明 (ZH)';
        enterDescriptionZH = '請輸入中文描述';
        enterMinParticipants = '輸入最少參與者';
        enterMaxParticipants = '輸入最大參與者數';
        eventDays = '活動日';
        date = '日期';
        selectDate = '請選擇日期';
        startTime = '開始時間';
        selectStartTime = '請選擇開始時間';
        endTime = '結束時間';
        selectEndTime = '請選擇結束時間';
        location = '地點';
        enterLocation = '請輸入位置';
        federalState = '聯邦國家';
        enterFederalState = '請輸入聯邦州';
        removeDay = '刪除日期';
        addEventDay = '新增另一個活動日';
        createEvent = '建立事件';
        break;
      default:
        appTitle = 'Skillforge';
        hompageTitle = 'Skillforge';
        english = 'en';
        chinese = 'zh';
        german = 'de';
        yearLabel = 'Year';
        monthLabel = 'Month';
        weekLabel = 'Week';
        resetLabel = 'Reset';
        invalidCaptcha = 'Invalid captcha. Please try again.';
        failedLogin = 'Login failed';
        networkError = 'Network error. Please try again.';
        login = 'Login';
        username = 'Username';
        insertUsername = 'Please enter a username';
        password = 'Password';
        insertPassword = 'Please enter a password';
        captcha = 'Input Captcha';
        insertCaptcha = 'Please enter the Captcha code';
        wrongCaptcha = 'Invalid Captcha code';
        rememberMe = 'Remember me';
        loginSuccessful = 'Login successful. Hello,';
        logoutSuccessful = 'Logout successful. See you soon';
        forgotPassword = 'Forgot password?';
        resetPassword = 'Reset password';
        filterOptions = 'Filter Options';
        filterByUser = 'Show only my events';
        loginToFilter = 'Please log in to filter by user.';
        eventType = 'Event Type';
        subjectArea = 'Subject Area';
        clearFilters = 'Clear Filters';
        applyFilters = 'Apply Filters';
        newYear = 'New Year';
        firstMay = 'Labour Day';
        germanUnity = 'Anniversary of the German Unification';
        christmas1 = 'First Christmas Day';
        christmas2 = 'Second Christmas Day';
        carFriday = 'Good Friday';
        easterSunday = 'Easter Sunday';
        easterMonday = 'Easter Monday';
        christHeavenDrive = 'Ascension of Christ';
        whitSunday = 'Whit Sunday';
        whitMonday = 'Whit Monday';
        epiphany = 'Epiphany';
        intlWomen = 'International Women`s Day';
        happyCadaver = 'Corpus Christi';
        peaceParty = 'Augsburg`s High Festival of Peace';
        mariaHeavenDrive = 'Assumption Day';
        worldChildDay = 'World Children`s Day';
        reformationDay = 'Reformation Day';
        allSaints = 'All Saints` Day';
        failedToLoadEventDetails = 'Failed to load event details.';
        failedToCheckRegistrationStatus =
            'Failed to check registration status.';
        registrationSuccessful = 'Successfully registered for the event.';
        registrationFailed = 'Registration failed.';
        cancellationSuccessful = 'Successfully canceled your registration.';
        cancellationFailed = 'Cancellation failed.';
        appointmentDetails = 'Appointment Details';
        noEventDetails = 'No event details available.';
        cancelRegistration = 'Cancel Registration';
        registerForEvent = 'Register for Event';
        loginRequired = 'Login required to perform this action.';
        participants = 'Participants';
        eventDates = 'Event Dates';
        minParticipants = 'Min Participants';
        maxParticipants = 'Max Participants';
        currentParticipants = 'Current Participants';
        participantInfo = 'Participant Information';
        noAppointments = 'No appointments available';
        eventSuccessful = 'Event creation successful with ID:';
        eventNotSuccessful = 'Event creation failed';
        networkError2 = 'Network error:';
        accesDenied = 'Access denied';
        notAuthorized = 'You are not authorized to access this page.';
        adminPanel = 'Admin Panel for creating Events';
        autoTranslate = 'Auto Translate';
        inputLanguage = 'Input Language';
        nameDE = 'Name (DE)';
        enterStringDE = 'Please enter the name in German';
        nameEN = 'Name (EN)';
        enterStringEN = 'Please enter the name in English';
        nameZH = 'Name (ZH)';
        enterStringZH = 'Please enter the name in Chinese';
        descriptionDE = 'Description (DE)';
        enterDescriptionDE = 'Please enter the description in German';
        descriptionEN = 'Description (EN)';
        enterDescriptionEN = 'Please enter the description in English';
        descriptionZH = 'Description (ZH)';
        enterDescriptionZH = 'Please enter the description in Chinese';
        enterMinParticipants = 'Enter min participants';
        enterMaxParticipants = 'Enter max participants';
        eventDays = 'Event Days';
        date = 'Date';
        selectDate = 'Please select a date';
        startTime = 'Start Time';
        selectStartTime = 'Please select start time';
        endTime = 'End Time';
        selectEndTime = 'Please select end time';
        location = 'Location';
        enterLocation = 'Please enter a Location';
        federalState = 'Federal State';
        enterFederalState = 'Please enter a federal state';
        removeDay = 'Remove Day';
        addEventDay = 'Add another Event Day';
        createEvent = 'Create Event';
    }
  }
}

class Language {
  String identifier = '';
  String icon = '';
  Language(this.identifier, this.icon);
}

final german = Language(
  'de',
  '🇩🇪',
);
final english = Language(
  'en',
  '🇬🇧',
);
final chinese = Language(
  'zh',
  '🇨🇳',
);
