name: Build and Push Docker Images

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push backend image
        uses: docker/build-push-action@v4
        with:
          context: ./backend
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/skillforge-python-backend:latest

      - name: Build and push flutter_web image
        uses: docker/build-push-action@v4
        with:
          context: ./flutter_app
          dockerfile: Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/skillforge-flutter-web-app:latest
